# Copyright (c) godot-rust; Bromeon and contributors.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# The URL the site will be built for
base_url = "https://godot-rust.github.io"

title = "godot-rust: Rust bindings for Godot game engine"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# We don't want to generate a site wide feed, but only one for the devlog.
generate_feeds = false

# The filename to use for the feed. Used as the template filename, too.
# Defaults to "atom.xml", which has a built-in template that renders an Atom 1.0 feed.
# There is also a built-in template "rss.xml" that renders an RSS 2.0 feed.
feed_filenames = ["atom.xml"]

#taxonomies = [
#    {name = "tags", paginate_by = 5, feed = true},
#    {name = "categories", paginate_by = 5, feed = true},
#]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# A list of directories used to search for additional `.sublime-syntax` and `.tmTheme` files.
# More on https://www.getzola.org/documentation/getting-started/configuration/#syntax-highlighting.
extra_syntaxes_and_themes = []

# The theme to use for code highlighting.
# See below for list of allowed values.

# Similar ones in style.
#highlight_theme = "charcoal"
#highlight_theme = "one-dark"
highlight_theme = "two-dark"
#highlight_theme = "agola-dark"
#highlight_theme = "nyx-bold"

# Other options that might potentially fit.
# highlight_theme = "1337"
# highlight_theme = "ayu-mirage"
# highlight_theme = "base16-atelierdune-light"
# highlight_theme = "base16-ocean-dark"
# highlight_theme = "cheerfully-light"
# highlight_theme = "demain"
# highlight_theme = "dimmed-fluid"
# highlight_theme = "gruvbox-dark"
# highlight_theme = "inspired-github"
# highlight_theme = "ir-white"
# highlight_theme = "kronuz"
# highlight_theme = "nord"
# highlight_theme = "Tomorrow"


[extra]
enable_search = false
enable_sidebar = false
enable_adsense = false
enable_multilingue = false
#adsense_link = "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=myclientid"

[extra.navbar]
title = "godot-rust"
items = [
    { lang = "en", links = [
        { url = "/", name = "Home" },
        { url = "https://github.com/godot-rust/gdext", name = "GitHub" },
        { url = "/book", name = "Book" },
        { url = "/docs", name = "API Docs" },
        { url = "/dev", name = "Devlog" },
        { url = "https://github.com/sponsors/Bromeon", name = "♡" },
    ] }
]

#[extra.lang]
#items = [
#    { lang = "en", links = [
#        { base_url = "/", name = "English" },
#        { base_url = "/fr", name = "French" },
#    ] },
#    { lang = "fr", links = [
#        { base_url = "/", name = "Anglais" },
#        { base_url = "/fr", name = "Français" },
#    ] },
#]

#[extra.sidebar]
#items = [
#    { lang = "en", links = [
#        { url = "/markdown", name = "Markdown" },
#        { url = "/blog", name = "Blog" },
#    ] }
#]

# Index page
[extra.index]
title = "Main title"
image = "https://via.placeholder.com/200"
image_alt = "Placeholder text describing the index's image."


[extra.links]
github = "https://github.com/godot-rust/gdext"

[extra.social]
discord = "https://discord.gg/aKUCJ8rJsc"
mastodon = "https://mastodon.gamedev.place/@GodotRust"
bluesky = "https://bsky.app/profile/godot-rust.bsky.social"
twitter = "https://twitter.com/GodotRust"


# Possibly interesting: https://stackoverflow.com/a/68051929
[extra.favicon]
#favicon = "/favicon-16x16.png"
favicon_16x16 = "/icons/favicon-16x16.png"
favicon_32x32 = "/icons/favicon-32x32.png"
apple_touch_icon = "/icons/apple-touch-icon.png"
android_chrome_512 = "/icons/android-chrome-512x512.png"
android_chrome_192 = "/icons/android-chrome-192x192.png"
manifest = "/icons/site.webmanifest"
